services:
  spring-service:
    env_file:
      - .env
    container_name: spring-container
    image: hyeesw/booktalk-spring:latest
    ports:
      - "8080:8080"
      - "80:8080"
    depends_on:
      mysql-service:
        condition: service_healthy
      redis-service:
        condition: service_healthy
    networks:
      - backend-network

  mysql-service:
    container_name: mysql-container
    image: mysql:latest
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Github secrete key
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    networks:
      - backend-network
    volumes:
      - ./mysql/data:/var/lib/mysql # mysql-container 가 생성한 데이터를 /home/ubuntu/git/mysql/data 폴더에 저장
      - ./mysql:/etc/mysql/conf.d # 서버 /home/ubuntu/git/mysql 폴더에 있는 설정 파일을 컨테이너 내부의 /etc/mysql/conf.d 폴더에 복사
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d # src/main/resources/sql 폴더에 있는 script 파일을 컨테이너 내부의 /docker-entrypoint-initdb.d 폴더에 복사

  redis-service:
    container_name: redis-container
    host : redis-container # docker 에서 이 이름으로 reids 와 연결
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - backend-network
    command: redis-server --save 60 1000 --requirepass ${REDIS_PASSWORD}
    volumes: # 마운트할 볼륨 설정
      - ./redis/data:/data # redis-container 가 생성한 데이터를 /home/ubuntu/git/redis/data 폴더에 저장
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf # 서버 /home/ubuntu/git/redis/redis.conf 파일을 컨테이너 내부의 /usr/local/etc/redis/redis.conf 파일에 복사

  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest  # Business Edition
    ports:
      - "18000:8000"
      - "19000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - PORTAINER_ARGS=--ssl --sslcert /certs/portainer.crt --sslkey /certs/portainer.key --tunnel-port=8000 --tunnel-certificate /certs/portainer.crt --tunnel-key /certs/portainer.key
      - PORTAINER_ENCRYPTION_KEY=${PORTAINER_ENCRYPTION_KEY}
    restart: always

volumes:
  portainer_data:

networks:
  backend-network:
