server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # JPA 말고 flyway 로 DB 초기화

  sql: #data.sql 의 DDL 실행
    init:
      encoding: utf-8
      mode: always # initial script 실행

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

spring-doc:
  swagger-ui:
    tags-sorter: alpha # tag 순서 - 알파벳
    operations-sorter : method # HTTP 메소드 순서
    doc-expansion : none # 펼치지 않기

openapi:
  url: ${OPENAPI_URL}
  authKey: ${OPENAPI_AUTH_KEY}

kakao:
  publicKeyUri: https://kauth.kakao.com/.well-known/jwks.json

apple:
  publicKeyUri: https://appleid.apple.com/auth/keys

jwt:
  secretKey: ${JWT_SECRET}
  accessTokenExpireTime: ${ACCESS_TOKEN_EXPIRE_TIME}
  refreshTokenExpireTime: ${REFRESH_TOKEN_EXPIRE_TIME}

isLocal: ${IS_LOCAL}
