server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # entity 기반 스키마 생성 // update 로 변경

    properties:
      hibernate:
        globally_quoted_identifiers: true # sql 예약어와 일치하는 필드명 구분
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true # ddl-auto 실행 후 data.sql 로 데이터 삽입

  sql: #data.sql 의 DDL 실행
    init:
      mode: always
      data-locations: classpath:data.sql, classpath:dummy.sql

openapi:
  url: ${OPENAPI_URL}
  authKey: ${OPENAPI_AUTH_KEY}

kakao:
  restapiKey: ${RESTAPI_KEY}
  redirectUri: http://localhost:8080/login/oauth2/kakao
  tokenRequestUri: https://kauth.kakao.com/oauth/token
  userInfoUri: https://kapi.kakao.com/v2/user/me

jwt:
  secretKey: ${JWT_SECRET}
  accessTokenExpireTime: ${ACCESS_TOKEN_EXPIRE_TIME}
  refreshTokenExpireTime: ${REFRESH_TOKEN_EXPIRE_TIME}
